apiVersion: v1
kind: Pod
metadata:
  name: psql-pod
  namespace: aninaka
spec:
  containers:
    - name: psql
      image: postgres:13.2
      env:
        - name: POSTGRES_PASSWORD
          value: pgpwd
