apiVersion: v1
kind: Service
metadata:
  name: aninaka-user-auth-api
  namespace: aninaka
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: aninaka-user-auth-api
  type: NodePort
